### PR TITLE
feat(norm): introduce convetional commit

### PR DESCRIPTION
**Pull request by pplmx**
for a undified commit message style, please use `npm run commit` to replace `git commit`

### CODE REVIEW

**Comment by jiangtj** [comment]
It may not be necessary to add commitizen, perhaps the content of PR should be regulated, but git commit in PR is not important. I usually use squash, these commits will not appear in the master branch

image

**Comment by pplmx** [comment]
okay, it's just advice. :) 😄

**Comment by jiangtj** [comment]
BTW, if you use `npm`, add `package-lock.json` to `.gitignore` 😂

**Comment by pplmx** [comment]
Got it. 💯 😆

**Pull request closed without merging**
